services:
  waha:
    image: devlikeapro/waha:arm
    container_name: wpp_bot_waha
    restart: always

    ports:
      - '3000:3000'

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: wpp_bot_api
    ports:
      - '6000:6000'
    # volumes:
    #   - .:/app
    #   - ./chroma_data:/app/chroma_data